apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-o4xi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-o4xi
    app.kubernetes.io/part-of: cin4s-839-0049-app
  name: devfile-sample-o4xi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-o4xi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-o4xi
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0049-tenant/cin4s-839-0049-app/devfile-sample-o4xi@sha256:ec2e3e9e970dc1cfb806bf18ae8251cce0a40893b0481347e13ce23a7700567f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
